services:
  travel_hi_api:
    build:
      context: ./api
      dockerfile: Dockerfile    # Twój Dockerfile API
    env_file:
      - ./api/.envs/.env
    working_dir: /api
    networks: [default]
    volumes:
      - ./api:/api              # jeśli chcesz hot-reload w DEV; w PROD usuń
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health >/dev/null || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 60s
    restart: unless-stopped

  frontend:
    build:
      context: ./app
      # przekaż zmienne na czas builda (Vite):
      args:
        VITE_API_URL: /api
    depends_on:
      travel_hi_api: { condition: service_healthy }
    ports:
      - "8080:80"               # -> http://127.0.0.1:8080
    restart: unless-stopped

networks:
  default:
    driver: bridge